server:
  port: 8888

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

turbine:
  appConfig: easylearn-edge
  clusterNameExpression: "'default'"